CREATE TABLE IF NOT EXISTS "primary_weapons" (
"index" INTEGER,
  "weapon" TEXT,
  "tier" TEXT
);
INSERT INTO primary_weapons VALUES(0,'KUVA ZARR','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(1,'NATARUK','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(2,'PROBOSCIS CERNOS','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(3,'KUVA BRAMMA','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(4,'CEDO','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(5,'TENET ARCA PLASMOR','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(6,'RUBICO PRIME','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(7,'PHENMOR','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(8,'BUBONICO','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(9,'ACCELTRA','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(10,'IGNIS WRAITH','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(11,'TRUMNA','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(12,'TENET ENVOY','S Tier - Prime Time');
INSERT INTO primary_weapons VALUES(13,'KUVA KOHM','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(14,'KUVA OGRIS','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(15,'KUVA CHAKKHURR','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(16,'CORINTH PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(17,'STAHLTA','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(18,'FULMIN','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(19,'VECTIS PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(20,'PHANTASMA','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(21,'SHEDU','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(22,'ASTILLA PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(23,'TENET FLUX RIFLE','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(24,'AMPREX','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(25,'TENET TETRA','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(26,'FELARX','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(27,'SCOURGE PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(28,'KUVA HEK','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(29,'TENORA PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(30,'OPTICOR VANDAL','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(31,'SOMA PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(32,'KUVA TONKOR','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(33,'BAZA PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(34,'STRUN PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(35,'TIGRIS PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(36,'TIBERON PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(37,'AEOLAK','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(38,'LENZ','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(39,'VAYKOR HEK','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(40,'KUVA QUARTAKK','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(41,'ZENITH','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(42,'ARCA PLASMOR','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(43,'EXERGIS','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(44,'SUPRA VANDAL','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(45,'NAGANTAKA PRIME','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(46,'DREAD','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(47,'SYNAPSE','A Tier - Strong Picks');
INSERT INTO primary_weapons VALUES(48,'KUVA HIND','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(49,'KUVA KARAK','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(50,'AMBASSADOR','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(51,'BASMU','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(52,'SYBARIS PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(53,'QUELLOR','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(54,'CERNOS PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(55,'LANKA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(56,'PHAGE','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(57,'ZHUGE PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(58,'PRISMA GRAKATA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(59,'KOMOREX','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(60,'BATTACOR','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(61,'PANTHERA PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(62,'SANCTI TIGRIS','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(63,'SPOROTHRIX','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(64,'CORINTH','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(65,'KOHM','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(66,'KUVA DRAKGOON','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(67,'GLAXION VANDAL','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(68,'BOAR PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(69,'MUTALIST CERNOS','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(70,'DAIKYU','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(71,'PRISMA GRINLOK','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(72,'BOLTOR PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(73,'OPTICOR','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(74,'STRADAVAR PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(75,'RAKTA CERNOS','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(76,'ASTILLA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(77,'STRUN WRAITH','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(78,'SECURA PENTA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(79,'HEK','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(80,'FERROX','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(81,'QUANTA VANDAL','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(82,'PRISMA GORGON','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(83,'TENORA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(84,'ZARR','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(85,'DEX SYBARIS','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(86,'SYNOID SIMULOR','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(87,'CONVECTRIX','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(88,'RUBICO','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(89,'TELOS BOLTOR','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(90,'SCOURGE','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(91,'IGNIS','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(92,'VECTIS','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(93,'SOBEK','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(94,'VULKAR WRAITH','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(95,'PARIS PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(96,'HEMA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(97,'SNIPETRON VANDAL','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(98,'BAZA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(99,'LATRON PRIME','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(100,'ALTERNOX','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(101,'NAGANTAKA','B Tier - Good Picks');
INSERT INTO primary_weapons VALUES(102,'BRATON PRIME','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(103,'SOMA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(104,'TONKOR','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(105,'TIGRIS','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(106,'KARAK WRAITH','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(107,'BRATON VANDAL','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(108,'BUZLOK','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(109,'LATRON WRAITH','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(110,'ARGONAK','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(111,'MITER','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(112,'OGRIS','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(113,'ATTICA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(114,'TORID','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(115,'GRAKATA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(116,'SUPRA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(117,'CARMINE PENTA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(118,'PRISMA TETRA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(119,'MUTALIST QUANTA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(120,'GORGON WRAITH','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(121,'BURSTON PRIME','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(122,'QUARTAKK','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(123,'DERA VANDAL','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(124,'DRAKGOON','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(125,'ZHUGE','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(126,'PARACYST','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(127,'SYBARIS','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(128,'STRADAVAR','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(129,'TIBERON','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(130,'BOLTOR','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(131,'JAVLOK','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(132,'SIMULOR','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(133,'PANTHERA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(134,'CERNOS','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(135,'FLUX RIFLE','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(136,'VELDT','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(137,'GLAXION','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(138,'HARPAK','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(139,'KARAK','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(140,'GRINLOK','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(141,'SNIPETRON','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(142,'PENTA','C Tier - Average Picks');
INSERT INTO primary_weapons VALUES(143,'MK1-BRATON','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(144,'MK1-STRUN','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(145,'VULKAR','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(146,'QUANTA','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(147,'PARIS','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(148,'STRUN','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(149,'BOAR','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(150,'MK1-PARIS','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(151,'GORGON','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(152,'TETRA','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(153,'LATRON','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(154,'BRATON','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(155,'HIND','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(156,'DERA','D Tier - Weak Picks');
INSERT INTO primary_weapons VALUES(157,'BURSTON','D Tier - Weak Picks');
CREATE TABLE IF NOT EXISTS "secondary_weapons" (
"index" INTEGER,
  "weapon" TEXT,
  "tier" TEXT
);
INSERT INTO secondary_weapons VALUES(0,'KUVA NUKOR','S Tier - Prime Time');
INSERT INTO secondary_weapons VALUES(1,'LAETUM','S Tier - Prime Time');
INSERT INTO secondary_weapons VALUES(2,'SPORELACER','S Tier - Prime Time');
INSERT INTO secondary_weapons VALUES(3,'TENET CYCRON','S Tier - Prime Time');
INSERT INTO secondary_weapons VALUES(4,'EPITAPH','S Tier - Prime Time');
INSERT INTO secondary_weapons VALUES(5,'PYRANA PRIME','S Tier - Prime Time');
INSERT INTO secondary_weapons VALUES(6,'KUVA BRAKK','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(7,'KNELL PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(8,'CATCHMOON','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(9,'TOMBFINGER','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(10,'AKSOMATI PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(11,'CATABOLYST','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(12,'VERMISPLICER','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(13,'TENET DIPLOS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(14,'GAZE','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(15,'AKJAGARA PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(16,'RATTLEGUTS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(17,'EUPHONA PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(18,'KUVA TWIN STUBBAS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(19,'TENET DETRON','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(20,'TENET SPIREX','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(21,'ATHODAI','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(22,'AKSTILETTO PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(23,'SEPULCRUM','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(24,'ZAKTI PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(25,'PANDERO PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(26,'STATICOR','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(27,'ZYMOS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(28,'KOMPRESSA','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(29,'ATOMOS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(30,'TWIN GRAKATAS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(31,'AKARIUS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(32,'SYNOID GAMMACOR','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(33,'MARA DETRON','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(34,'MAGNUS PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(35,'PRISMA TWIN GREMLINS','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(36,'SICARUS PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(37,'VELOX','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(38,'CYANEX','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(39,'KUVA SEER','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(40,'AKVASTO PRIME','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(41,'TWIN KOHMAK','A Tier - Strong Picks');
INSERT INTO secondary_weapons VALUES(42,'AKLEX PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(43,'AKBOLTO PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(44,'SPIRA PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(45,'PANDERO','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(46,'VAYKOR MARELOK','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(47,'LATO PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(48,'POX','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(49,'ARCA SCISCO','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(50,'LEX PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(51,'HYSTRIX','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(52,'LATO VANDAL','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(53,'KUVA KRAKEN','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(54,'VASTO PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(55,'OCUCOR','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(56,'DEX FURIS','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(57,'HIKOU PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(58,'AKBRONCO PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(59,'SPECTRA VANDAL','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(60,'TWIN ROGGA','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(61,'KNELL','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(62,'QUATZ','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(63,'BALLISTICA PRIME','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(64,'AZIMA','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(65,'SECURA DUAL CESTRA','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(66,'DUAL TOXOCYST','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(67,'TYSIS','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(68,'PRISMA ANGSTRUM','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(69,'NUKOR','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(70,'AKSOMATI','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(71,'PYRANA','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(72,'SANCTI CASTANAS','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(73,'ZAKTI','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(74,'SONICOR','B Tier - Good Picks');
INSERT INTO secondary_weapons VALUES(75,'KULSTAR','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(76,'PLINX','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(77,'RAKTA BALLISTICA','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(78,'TELOS AKBOLTO','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(79,'AKMAGNUS','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(80,'EMBOLIST','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(81,'KOHMAK','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(82,'BRONCO PRIME','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(83,'FUSILAI','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(84,'DESPAIR','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(85,'AKZANI','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(86,'AKSTILETTO','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(87,'STUBBA','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(88,'BRAKK','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(89,'ZYLOK','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(90,'CYCRON','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(91,'MARELOK','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(92,'AKLEX','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(93,'AKJAGARA','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(94,'ACRID','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(95,'DUAL CESTRA','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(96,'AKVASTO','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(97,'DETRON','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(98,'GAMMACOR','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(99,'STUG','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(100,'TWIN VIPERS WRAITH','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(101,'SPIRA','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(102,'MAGNUS','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(103,'HIKOU','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(104,'TWIN GREMLINS','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(105,'AFURIS','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(106,'FURIS','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(107,'LEX','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(108,'VASTO','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(109,'ANGSTRUM','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(110,'VIPER WRAITH','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(111,'AKBOLTO','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(112,'TALONS','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(113,'CESTRA','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(114,'SPECTRA','C Tier - Average Picks');
INSERT INTO secondary_weapons VALUES(115,'CASTANAS','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(116,'SICARUS','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(117,'SEER','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(118,'MK1-KUNAI','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(119,'KRAKEN','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(120,'KUNAI','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(121,'BOLTO','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(122,'LATO','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(123,'AKLATO','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(124,'AKBRONCO','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(125,'BALLISTICA','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(126,'BRONCO','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(127,'TWIN VIPERS','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(128,'MK1-FURIS','D Tier - Weak Picks');
INSERT INTO secondary_weapons VALUES(129,'VIPER','D Tier - Weak Picks');
CREATE TABLE IF NOT EXISTS "melee_weapons" (
"index" INTEGER,
  "weapon" TEXT,
  "tier" TEXT
);
INSERT INTO melee_weapons VALUES(0,'NIKANA PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(1,'KRONEN PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(2,'GUANDAO PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(3,'STROPHA','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(4,'GLAIVE PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(5,'REAPER PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(6,'REDEEMER PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(7,'SEPFAHN','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(8,'VENKA PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(9,'GRAM PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(10,'PRAEDOS','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(11,'PLAGUE KRIPATH','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(12,'ORTHOS PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(13,'INNODEM','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(14,'LESION','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(15,'NAMI SKYLA PRIME','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(16,'PARACESIS','S Tier - Prime Time');
INSERT INTO melee_weapons VALUES(17,'TENET GRIGORI','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(18,'NEPHERI','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(19,'TENET LIVIA','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(20,'VITRICA','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(21,'DOKRAHM','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(22,'PANGOLIN PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(23,'PENNANT','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(24,'KUVA SHILDEG','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(25,'SILVA & AEGIS PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(26,'KARYST PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(27,'GALATINE PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(28,'BROKEN WAR','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(29,'BALLA','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(30,'PLAGUE KEEWAR','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(31,'TENET AGENDUS','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(32,'HESPAR','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(33,'SKIAJATI','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(34,'CYATH','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(35,'VASTILOK','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(36,'TENET EXEC','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(37,'QUASSUS','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(38,'VERDILAC','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(39,'CETI LACERA','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(40,'JAT KUSAR','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(41,'HATE','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(42,'TELOS BOLTACE','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(43,'VOLNUS PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(44,'DUAL KAMAS PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(45,'NINKONDI PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(46,'DAKRA PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(47,'DESTREZA PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(48,'FRAGOR PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(49,'RAKTA DARK DAGGER','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(50,'PRISMA DUAL CLEAVERS','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(51,'WAR','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(52,'TATSU','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(53,'DRAGON NIKANA','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(54,'XORIS','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(55,'DUAL KERES','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(56,'HIRUDO','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(57,'KERATINOS','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(58,'TWIN KROHKUR','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(59,'VENATO','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(60,'SIGMA & OCTANTIS','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(61,'TIPEDO PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(62,'OHMA','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(63,'TEKKO PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(64,'ARCA TITRON','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(65,'KORUMM','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(66,'SCINDO PRIME','A Tier - Strong Picks');
INSERT INTO melee_weapons VALUES(67,'WOLF SLEDGE','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(68,'HALIKAR WRAITH','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(69,'OOLTHA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(70,'SKANA PRIME','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(71,'MACHETE WRAITH','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(72,'DUAL ICHOR','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(73,'CAUSTACYST','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(74,'ATTERAX','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(75,'PATHOCYST','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(76,'FANG PRIME','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(77,'SANCTI MAGISTAR','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(78,'VERICRES','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(79,'PULMONARS','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(80,'MIOS','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(81,'KOGAKE PRIME','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(82,'GUANDAO','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(83,'PRISMA SKANA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(84,'ARUM SPINOSA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(85,'TWIN BASOLK','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(86,'MEWAN','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(87,'CERATA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(88,'DEX DAKRA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(89,'DARK SPLIT-SWORD','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(90,'BO PRIME','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(91,'ZENISTAR','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(92,'RUMBLEJACK','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(93,'JAT KITTAG','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(94,'DEHTAT','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(95,'CASSOWAR','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(96,'VOLNUS','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(97,'MIRE','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(98,'SYNOID HELIOCOR','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(99,'RABVEE','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(100,'GALATINE','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(101,'SARPA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(102,'DUAL ETHER','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(103,'SECURA LECTA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(104,'PRISMA OBEX','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(105,'GUNSEN','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(106,'VAYKOR SYDON','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(107,'KROHKUR','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(108,'KRONEN','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(109,'SCOLIAC','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(110,'REDEEMER','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(111,'ACK & BRUNT','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(112,'COBRA & CRANE','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(113,'NIKANA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(114,'CADUS','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(115,'PRISMA MACHETE','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(116,'LACERA','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(117,'KRONSH','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(118,'RIPKAS','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(119,'FURAX WRAITH','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(120,'ETHER REAPER','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(121,'ORVIUS','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(122,'FALCOR','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(123,'KORRUDO','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(124,'ANKYROS PRIME','B Tier - Good Picks');
INSERT INTO melee_weapons VALUES(125,'MASSETER','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(126,'SILVA & AEGIS','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(127,'BROKEN SCEPTER','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(128,'ORTHOS','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(129,'AMPHIS','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(130,'TONBO','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(131,'HELIOCOR','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(132,'ENDURA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(133,'TIPEDO','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(134,'GAZAL MACHETE','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(135,'PROVA VANDAL','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(136,'NINKONDI','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(137,'PUPACYST','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(138,'GHOULSAW','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(139,'GRAM','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(140,'DUAL ZOREN','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(141,'BOLTACE','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(142,'OKINA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(143,'DUAL RAZA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(144,'DUAL CLEAVERS','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(145,'KESHEG','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(146,'SERRO','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(147,'ANKU','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(148,'ETHER DAGGERS','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(149,'VENKA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(150,'DESTREZA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(151,'SIBEAR','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(152,'KRESKA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(153,'SHEEV','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(154,'DARK SWORD','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(155,'JAW SWORD','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(156,'KARYST','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(157,'TEKKO','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(158,'HEAT SWORD','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(159,'DUAL KAMAS','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(160,'GALVACORD','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(161,'SKANA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(162,'NAMI SKYLA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(163,'HALIKAR','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(164,'SHAKU','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(165,'DUAL HEAT SWORDS','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(166,'ETHER SWORD','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(167,'GLAIVE','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(168,'SCINDO','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(169,'DUAL SKANA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(170,'DARK DAGGER','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(171,'PLASMA SWORD','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(172,'PANGOLIN SWORD','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(173,'SYDON','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(174,'LECTA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(175,'PROVA','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(176,'NAMI SOLO','C Tier - Average Picks');
INSERT INTO melee_weapons VALUES(177,'FRAGOR','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(178,'KAMA','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(179,'MK1-BO','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(180,'CERAMIC DAGGER','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(181,'OBEX','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(182,'CRONUS','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(183,'MAGISTAR','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(184,'HEAT DAGGER','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(185,'MACHETE','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(186,'BO','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(187,'FANG','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(188,'MK1-FURAX','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(189,'KESTREL','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(190,'FURAX','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(191,'KOGAKE','D Tier - Weak Picks');
INSERT INTO melee_weapons VALUES(192,'ANKYROS','D Tier - Weak Picks');
